# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      pwd
      
      mkdir downloads
      
      cd downloads
      
      curl -O https://download.java.net/openjdk/jdk13/ri/openjdk-13+33_linux-x64_bin.tar.gz
      
      ls /builds
      
      ls /builds/downloads
      
      echo "Done"
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '13'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '/builds/downloads/openjdk-13+33_linux-x64_bin.tar.gz'
    jdkDestinationDirectory: 'build/jdk'
    cleanDestinationDirectory: true